In [1]:
## Dataset Airbnb

In [3]:
import pandas as pd

In [7]:
df = pd.read_csv("listings.csv")
df

,id,nombre,id_anfitrion,nombre_anfitrion,grupo_colonia,colonia,latitud,longitud,tipo_habitacion,precio,noches_minimas,numero_resenas,ultima_resena,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm,license
0,35797,Villa Dante,153786,Dici,NaN,Cuajimalpa de Morelos,19.382830,-99.271780,Entire home/apt,3673.0,1,0,NaN,NaN,1,363,0,NaN
1,44616,Condesa Haus,196253,Fernando,NaN,Cuauhtémoc,19.411620,-99.177940,Entire home/apt,18000.0,1,65,2025-01-01,0.38,9,360,1,NaN
2,56074,Great space in historical San Rafael,265650,Maris,NaN,Cuauhtémoc,19.439770,-99.156050,Entire home/apt,591.0,15,84,2025-02-27,0.48,1,333,1,NaN
3,67703,"2 bedroom apt. deco bldg, Condesa",334451,Nicholas,NaN,Cuauhtémoc,19.411520,-99.168570,Entire home/apt,NaN,2,50,2024-10-30,0.30,2,252,1,NaN
4,70644,Beautiful light Studio Coyoacan- full equipped !,212109,Trisha,NaN,Coyoacán,19.354480,-99.162170,Entire home/apt,NaN,3,134,2025-08-18,0.81,3,234,8,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27046,1518356968266486778,Suite Frida,674644167,Heyliana,NaN,Venustiano Carranza,19.442240,-99.113440,Private room,1096.0,1,0,NaN,NaN,5,365,0,NaN
27047,1518388105556721163,Habitación a un costado de Ciudad Universitaria,222854336,Marco Antonio,NaN,Coyoacán,19.308017,-99.168158,Private room,260.0,1,0,NaN,NaN,1,365,0,NaN
27048,1518433354720281854,Espacioso departamento en Anzures,470800231,Hector Fernando,NaN,Miguel Hidalgo,19.434460,-99.174010,Entire home/apt,996.0,1,0,NaN,NaN,20,365,0,NaN
27049,1518462568893975567,Casa Roma Baja 05,710857718,Camila,NaN,Cuauhtémoc,19.406435,-99.160934,Entire home/apt,458.0,1,0,NaN,NaN,7,363,0,NaN
27050,1518561444972990747,Departamento con Terraza privada Roma Norte,362149590,Ilse,NaN,Cuauhtémoc,19.413682,-99.154815,Entire home/apt,3082.0,1,0,NaN,NaN,4,365,0,NaN

In [8]:
df.shape

(27051, 18)

In [9]:
df.columns

Index(['id', 'nombre', 'id_anfitrion', 'nombre_anfitrion', 'grupo_colonia',
       'colonia', 'latitud', 'longitud', 'tipo_habitacion', 'precio',
       'noches_minimas', 'numero_resenas', 'ultima_resena', 'resenas_por_mes',
       'propiedades_anfitrion', 'disponibilidad_365', 'number_of_reviews_ltm',
       'license'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27051 entries, 0 to 27050
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     27051 non-null  int64
 1   nombre                 27051 non-null  object
 2   id_anfitrion           27051 non-null  int64
 3   nombre_anfitrion       27045 non-null  object
 4   grupo_colonia          0 non-null      float64
 5   colonia                27051 non-null  object
 6   latitud                27051 non-null  float64
 7   longitud               27051 non-null  float64
 8   tipo_habitacion        27051 non-null  object
 9   precio                 23567 non-null  float64
 10  noches_minimas         27051 non-null  int64
 11  numero_resenas         27051 non-null  int64
 12  ultima_resena          23650 non-null  object
 13  resenas_por_mes        23650 non-null  float64
 14  propiedades_anfitrion  27051 non-null  int64
 15  disponibilidad_365     27051 non-null  int64
 16  number_of_reviews_ltm  27051 non-null  int64
 17  license                0 non-null      float64
dtypes: float64(6), int64(7), object(5)
memory usage: 3.7+ MB

In [13]:
df.describe()

,id,id_anfitrion,grupo_colonia,latitud,longitud,precio,noches_minimas,numero_resenas,resenas_por_mes,propiedades_anfitrion,disponibilidad_365,number_of_reviews_ltm,license
count,2.705100e+04,2.705100e+04,0.0,27051.000000,27051.000000,23567.000000,27051.000000,27051.000000,23650.000000,27051.000000,27051.000000,27051.000000,0.0
mean,7.003556e+17,2.429439e+08,NaN,19.405490,-99.165385,1792.540841,4.580866,53.777679,1.854855,14.559868,232.686333,15.691028,NaN
std,5.702714e+17,2.062579e+08,NaN,0.042390,0.033535,13230.940558,24.784605,85.143043,2.281154,31.892178,122.270858,23.615517,NaN
min,3.579700e+04,7.365000e+03,NaN,19.177848,-99.339630,61.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000,NaN
25%,4.410472e+07,5.621443e+07,NaN,19.392489,-99.178499,643.000000,1.000000,4.000000,0.450000,1.000000,140.000000,0.000000,NaN
50%,8.307368e+17,1.766835e+08,NaN,19.415390,-99.167100,1039.000000,2.000000,21.000000,1.260000,3.000000,269.000000,7.000000,NaN
75%,1.217382e+18,4.288830e+08,NaN,19.432015,-99.153731,1611.000000,2.000000,69.000000,2.620000,11.000000,341.000000,23.000000,NaN
max,1.518561e+18,7.208445e+08,NaN,19.561010,-98.963360,900000.000000,1125.000000,1434.000000,119.460000,221.000000,365.000000,665.000000,NaN